### ISSUE TITLE
DLL Not Found Exception

### ISSUE THREAD

**Issue by hephaestus9** [RobyDX/SharpDX_Demo#7]
I am getting the following error:
> An unhandled exception of type 'System.DllNotFoundException' occurred in SharpDX.Direct3D11.dll
> 
> Additional information: Unable to load DLL 'd3dx11_43.dll': The specified module could not be found. > (Exception from HRESULT: 0x8007007E)

At line 95 in tutorial 18:
> g.Material.DiffuseTexture = ShaderResourceView.FromFile(device.Device, path + g.Material.DiffuseTextureName);

and line 105 in tutorial 5:
> ShaderResourceView texture = ShaderResourceView.FromFile(device.Device, "../../texture.bmp");

none of the tutorials 5-18 are working for this reason.

**Comment by RobyDX** [comment]
update repository
